spring:
  profiles:
    active: default

---
spring:
  profiles: default
  config:
    name: application-default
    location: classpath:/config/
  datasource:
    url: jdbc:h2:mem:default
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  flyway:
    enabled: true
    locations: classpath:db/migration

  main:
    allow-bean-definition-overriding: true

role-service:
  url: http://localhost:8082

---
spring:
  profiles: dev
  role-service:
    url: http://localhost:8083

---
spring:
  profiles: sit
  role-service:
    url: http://localhost:8084

---
spring:
  profiles: uat
  role-service:
    url: http://localhost:8085
